### ISSUE TITLE
Design and implement a brief ET validation "task"

### ISSUE THREAD

**Issue by oesteban** [TheAxonLab/HCPh-fMRI-tasks#27]
The idea is to run this after the main 9-point calibration before the DWI and then again before the resting state (after ET drift correction).

The task would start and end with a fixation point in the center, then change the position to the four corners of the screen and then some random positions (e.g., 5 positions). Finally, the fixation point would be rendered in the middle again before finishing.

**Comment by celprov** [comment]
@esavary Can I ask why we are implementing a custom validation ET task and not using the validation from the Eyelink?

**Comment by esavary** [comment]
We had to create custom validation because retrieving data from the ET computer was impossible.
