### ISSUE TITLE
Store data from all sessions in the same folder

### ISSUE THREAD

**Issue by esavary** [TheAxonLab/HCPh-fMRI-tasks#31]

**Comment by esavary** [comment]
I'd prefer to stick with the current code version, which creates individual folders for each session to store raw data. Psychopy generates many files for each run; if we put them all in the same folder, it could become quite large and hard to manage over time. This only affects raw data storage and doesn't impact the Datalad repository. What do you think @oesteban @acionca @celprov ?

**Comment by oesteban** [comment]
The folder creation has demonstrated very brittle, I'd prefer that output files are named in a way that makes it easy to see the session they were acquired.

**Comment by esavary** [comment]
Why brittle? The problem with the eye-tracker data persists regardless of whether we store it all in one folder as long as it's different from the './data' folder of the repo.

**Comment by esavary** [comment]
I'm currently addressing the final Psychopy issues for tomorrow's session. Before I proceed with the implementation, could you confirm if we're going with the one-folder solution? I have reservations, but I'll go for your solution.
